const mongoose = require('mongoose');

const ProfileSchema = new mongoose.Schema({
    user:{
        type: mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    company:{
        type:String
    },
    website:{
        type:String
    },
    location:{
        type:String
    },
    status:{
        type:String,
        unique:true
    },
    skills:{
        type:[String],
        unique:true
    },
    bio:{
        type:String
    },
    githubUsername:{
        type:String
    },
    experience:[{
        title:{
            type:String,
            unique:true
        },
        company:{
            type:String,
            unique:true
        },
        location:{
            type:String
        },
        from:{
            type:Date,
            unique:true
        },
        to:{
            type:Date
        },
        current:{
            type:Boolean,
            default:false
        },
        description:{
            type:String
        }
    }],
    education:[{
        school:{
            type:String,
            unique:true
        },
        degree:{
            type:String,
            unique:true
        },
        fieldOfStudy:{
            type:String,
            unique:true
        },
        from:{
            type:Date,
            unique:true
        },
        to:{
            type:Date
        },
        current:{
            type:Boolean,
            default:false
        },
        description:{
            type:String
        }
    }],
    social:{
        youtube:{
            type:String
        },
        instagram:{
            type:String
        },
        facebook:{
            type:String
        },
        twitter:{
            type:String
        },
        linkedin:{
            type:String
        }
    },
    date:{
        type:Date,
        default:Date.now
    }
});

module.exports = Profile = mongoose.model('profile', ProfileSchema);